config/routes.rb
Rails.application.routes.draw do

  get 'visitor_app', to: 'visitor_app#index'


  get 'hello_world', to: 'hello_world#index'
  constraints Clearance::Constraints::SignedIn.new(&:admin?) do
    namespace :admin do
      resources :meats
      resources :sources
      resources :users
      resources :restaurants
      resources :restaurant_meats
      resource :new_restaurant_searches, only: %i(show create)
      root to: "users#index"
    end
  end

  root to: "restaurant_searches#show"

  resource :restaurant_searches, only: %i(show create)

  resources :restaurants, only: %i(index show)
  resources :sources, only: %i(index show)

  resources :passwords, controller: "clearance/passwords", only: %i(create new)
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: %i(create edit update)
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :restaurant_sources
  has_many :sources, through: :restaurant_sources

  has_many :restaurant_meats
  has_many :meats, through: :restaurant_meats

  validates :name, :api_id, :display_address,
            :phone, :coordinate, presence: true
end

app/controllers/admin/restaurants_controller.rb
module Admin
  class RestaurantsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:

    def new
      @new_restaurant = new_restaurant
      @restaurant = Restaurant.new
      super
    end

    def create
      @restaurant = build_restaurant
      if @restaurant.save
        flash[:notice] = "Restaruant added!"
      else
        flash[:error] = "Error in adding restaruant!"
      end
      redirect_to admin_restaurants_path
    end

    # def index
    #   super
    #   @resources = Restaurant.all.paginate(10, params[:page])
    # end
    private

    def build_restaurant
      Restaurant.new(restaurant_params)
    end

    def new_restaurant
      OpenStruct.new(new_restaurant_params)
    end

    def restaurant_params
      params[:restaurant][:display_address] = display_address_to_array
      params.require(:restaurant).permit!
    end

    def display_address_to_array
      params[:restaurant][:display_address].split("^^")
    end

    def new_restaurant_params
      params.require(:result).permit!
    end
    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Restaurant.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/views/restaurants/_restaurant.html.erb
<hr>
<div class="list-display">
  <p><%= restaurant.name  %></h4>
  <ul class="meats">
    Meats
    <% restaurant.meats.each do |meat| %>
      <li><%= meat.name %></li>
    <% end %>
  </ul>
  <ul class="sources">
  Sources
    <% restaurant.sources.each do |source| %>
      <li><%= source.name %></li>
    <% end %>
  </ul>
</div>

app/views/restaurants/index.html.erb
<ul class="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render 'restaurant', restaurant: restaurant %>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>New GOODmEATS Restaurant</h1>
<h2> <%= @new_restaurant.name %> </h2>
<p class="new-restaurant-address"><%= @new_restaurant.display_address.join(' ')  %></p>
<%= simple_form_for @restaurant do |form| %>
  <%= form.association :sources, label_method: :name, value_method: :id %>
  <%= form.association :meats, label_method: :name, value_method: :id %>
  <%= form.hidden_field :api_id, :value => @new_restaurant.api_id %>
  <%= form.hidden_field :name, :value => @new_restaurant.name %>
  <%= form.hidden_field :phone, :value => @new_restaurant.phone %>
  <%= form.hidden_field :coordinate, :value => @new_restaurant.coordinate.to_json %>
  <%= form.hidden_field :display_address,
    :value => @new_restaurant.display_address.join('^^') %>
  <%= form.submit "Submit" %>
<% end  %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name  %></h1>

<div class="contact">
  <ul>
    <% @restaurant.display_address.each do |item|   %>
      <li><%=  item  %></li>
  <% end  %>
  </ul>
</div>
<div class="sources">
  <h2 class="sources__header">Sources</h2>
  <ul>
    <% @restaurant.sources.each do |source|   %>
      <li class="source"><a href="<%= source_path(source) %>"><%=  source.name  %></li>
    <% end  %>
  </ul>
</div>