config/routes.rb
Rails.application.routes.draw do

  get 'visitor_app', to: 'visitor_app#index'


  get 'hello_world', to: 'hello_world#index'
  constraints Clearance::Constraints::SignedIn.new(&:admin?) do
    namespace :admin do
      resources :meats
      resources :sources
      resources :users
      resources :restaurants
      resources :restaurant_meats
      resource :new_restaurant_searches, only: %i(show create)
      root to: "users#index"
    end
  end

  root to: "restaurant_searches#show"

  resource :restaurant_searches, only: %i(show create)

  resources :restaurants, only: %i(index show)
  resources :sources, only: %i(index show)

  resources :passwords, controller: "clearance/passwords", only: %i(create new)
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: %i(create edit update)
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/new_restaurant_search.rb
require "yelp"

class NewRestaurantSearch
  include ActiveModel::Model

  attr_accessor :query, :location

  def initialize(attributes = {})
    super
    @search_service = YelpService
  end

  def results
    if has_query?
      search.map do |result|
        OpenStruct.new(result)
      end
    end
  end

  private

  def has_query?
    query.present? && location.present?
  end

  def search_query
    { query: query, location: location }
  end

  def search
    @search_service.search(search_query)
  end
end

app/controllers/admin/new_restaurant_searches_controller.rb
module Admin
  class NewRestaurantSearchesController < ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Meat.all.paginate(10, params[:page])
    # end

    def show
      @admin_new_restaurant_search = AdminNewRestaurantSearch.new(restaurant_search_params)
      @results = results
    end

    def create
      redirect_to admin_new_restaurant_searches_path(new_restaurant_search_params)
    end
    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Meat.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
    #
    private

    def restaurant_search_params
      params.permit(:query, :location)
    end

    def new_restaurant_search_params
      params.require(:admin_new_restaurant_search).permit(:query, :location)
    end

    def results
      @admin_new_restaurant_search.results
    end
  end
end

app/controllers/new_restaurant_searches_controller.rb
class NewRestaurantSearchesController < ApplicationController
  def show
    @new_restaurant_search = NewRestaurantSearch.new(restaurant_search_params)
    @results = results
  end

  def create
    redirect_to new_restaurant_searches_path(new_restaurant_search_params)
  end

  private

  def restaurant_search_params
    params.permit(:query, :location)
  end

  def new_restaurant_search_params
    params.require(:new_restaurant_search).permit(:query, :location)
  end

  def results
    @new_restaurant_search.results
  end
end

app/views/admin/new_restaurant_searches/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<header class="header">
  <h1 class="header__heading">Search for New Restaurants</h1>
  <div class="header__actions">
    <%= link_to 'Back', :back, class: "button" %>
  </div>
</header>

<div class="form-container">
  <%= form_for @admin_new_restaurant_search, class: "new-restaurant-searches-form" do |form| %>
    <fieldset>
      <%= form.label :query %>
      <%= form.text_field :query %>
      <%= form.label :location %>
      <%= form.text_field :location %>
      <%= form.submit "Search" %>
    </fieldset>
  <% end %>

  <ul>
    <% if @results %>
      <% @results.each do |result| %>
        <li class="new-restaurant">
          <p class="title">  <%= result.name %>
        <%= link_to 'Add restaurant', new_admin_restaurant_path(result: result.to_h)  %>
          </p>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>