config/routes.rb
Rails.application.routes.draw do

  get 'visitor_app', to: 'visitor_app#index'


  get 'hello_world', to: 'hello_world#index'
  constraints Clearance::Constraints::SignedIn.new(&:admin?) do
    namespace :admin do
      resources :meats
      resources :sources
      resources :users
      resources :restaurants
      resources :restaurant_meats
      resource :new_restaurant_searches, only: %i(show create)
      root to: "users#index"
    end
  end

  root to: "restaurant_searches#show"

  resource :restaurant_searches, only: %i(show create)

  resources :restaurants, only: %i(index show)
  resources :sources, only: %i(index show)

  resources :passwords, controller: "clearance/passwords", only: %i(create new)
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: %i(create edit update)
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <% if signed_in? %>
    Signed in as: <%= current_user.email %>
    <%= button_to 'Sign out', sign_out_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign in', sign_in_path %>
  <% end %>
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>
</div>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>